Introduce basic Location API based on postgres backend
codeforboston/vaccinatema pull request #23
Opened 2021-02-10 18:09 UTC by jonhines

2021-02-10 18:16 UTC, johndeyrup commented
Looks good 🚢

2021-02-10 18:19 UTC, johndeyrup commented on schema.sql
> +DROP TABLE IF EXISTS location_availability;
Maybe should have a note not to run this =)

2021-02-10 18:20 UTC, jonhines commented on schema.sql
> +DROP TABLE IF EXISTS location_availability;
great call.

will add

2021-02-10 18:21 UTC, jonhines commented on schema.sql
> +DROP TABLE IF EXISTS location_availability;
ill also remove the drop tables bits, that was only there for my benefit.

2021-02-10 18:34 UTC, jonhines commented on db/locations.js
> +  port: 5432,
@mzagaja reminder that we'll need to provide these values as part of the beanstalk deployment

2021-02-10 22:07 UTC, johndeyrup commented on db/locations.js
> +      'SELECT *, ' +
Is it worth abstracting the sql statements into another layer so we can reuse?

2021-02-10 22:14 UTC, johndeyrup commented on db/locations.js
> +const getLocationsCloseToGeo = async (homeLat, homeLong, rangeInMiles) => {
Doesn't have to be in this PR, but we probably want to either do a JOIN on availability and process the results into a single location or have a separate fetch for each location to fetch their associated availabilities.

2021-02-11 04:03 UTC, jonhines commented on db/locations.js
> +const getLocationsCloseToGeo = async (homeLat, homeLong, rangeInMiles) => {
i decided to migrate the location availability INTO the location table (so we have just one table now).

i felt like the additional table for just a single column was overkill for this and adding unnecessary complexity.

happy to talk it through some more if you think we still should keep it separate.

2021-02-11 13:26 UTC, johndeyrup commented on db/locations.js
> +const getLocationsCloseToGeo = async (homeLat, homeLong, rangeInMiles) => {
The problem with just having an array as availability is that it make the database a lot harder to work with. You have to send in the entire array of availabilities to make changes to availability and the availability column is the column that is going to grow the most. Usually storing arrays in sql quickly becomes unworkable. Additionally having a separate table makes it a lot easier to do historical work where we find out what sites had the most openings, the Globe wanted the historical data as well.

Joining the data is pretty straightforward. Here are a couple of queries that we are going to want to do.

http://sqlfiddle.com/#!17/4620c/4

2021-02-11 13:29 UTC, johndeyrup commented on routes/locations.js
> +    body('name').isLength({ min: 2 }),
Love the validators :+1:

2021-02-11 14:06 UTC, jonhines commented on db/locations.js
> +const getLocationsCloseToGeo = async (homeLat, homeLong, rangeInMiles) => {
ah ok this is great context.

i thought we were only ever capturing the latest availability for each location.  if we want to maintain a history, then that makes sense to me.

ill bring the second table back into the fold.

2021-02-11 16:24 UTC, jonhines commented on db/locations.js
> +const getLocationsCloseToGeo = async (homeLat, homeLong, rangeInMiles) => {
@johndeyrup just updated to bring back the availability data as a separate table.

2021-02-12 02:33 UTC, johndeyrup requested changes

2021-02-12 02:33 UTC, johndeyrup commented on dbschema.sql
> +  availabilitytime DATE,
Can we do a timestamp? Sql doesn't handle dates well

2021-02-12 02:33 UTC, johndeyrup commented on db/locations.js
> +const getLocationsCloseToGeo = async (homeLat, homeLong, rangeInMiles) => {
:+1:

2021-02-12 03:28 UTC, mzagaja commented
Just noting this now has some conflicts with app.js and might need a small rebase.

2021-02-12 14:37 UTC, jonhines commented on dbschema.sql
> +  availabilitytime DATE,
i left it as a DATE because it seems like time is not necessary as part of this reporting or display.  historically, ive never ran into issues with postgres handling this datatype for queries?

2021-02-12 14:50 UTC, johndeyrup commented on dbschema.sql
> +  availabilitytime DATE,
Epoch time is independent of time zone and can be handled server side in any language without any special parsing. I was storing dates that happened before 1970 I might use DateTime.

2021-02-12 15:05 UTC, jonhines commented on dbschema.sql
> +  availabilitytime DATE,
works for me.

just pushed to move to timestamp

2021-02-12 16:09 UTC, johndeyrup approved these changes

2021-02-12 17:01 UTC, merged